Repository openmsupply/conforma-server, pull requests merged in 2022-11, with the labels that each got.

#942 #66T Remove port requirement from single-instance servers
  docker/demo_server/nginx_config_single/default
Labels: Docs: Internal, Effort: 1, Epic #6: Query Syntax and Action plugin, Sprint#3

#938 #807 Keep template files linked to active template version
  database/buildSchema/43_views_functions_triggers.sql
Labels: Bug: development, Phase 2, Bugs during tests

#952 #951 #948 Fix migration / encrypted backups
  database/migration/migrateData.ts
  docker/demo_server/docker-compose.yml
  src/components/snapshots/useSnapshot.ts
Labels: Bug: development, Bug: production, Bugs during tests, Customer: Fiji, Customer: Angola

#944 #54T Proper back-end enforcement of review_assignments
  database/buildSchema/43_views_functions_triggers.sql
  plugins/action_generate_review_assignment_records/src/generateReviewAssignments.ts
Labels: Bug: development

#959 #956 Review locking simplifications
  database/buildSchema/27_review_assignment.sql
  database/buildSchema/32_review_status_history.sql
  database/buildSchema/43_views_functions_triggers.sql
  database/migration/migrateData.ts
  documentation/Database-Schema-Review-And-Consolidation.md
  plugins/action_generate_review_assignment_records/src/databaseMethods.ts
  plugins/action_generate_review_assignment_records/src/generateReviewAssignments.ts
  plugins/action_generate_review_assignment_records/src/types.ts
  plugins/action_update_review_status/package.json
  plugins/action_update_review_status/plugin.json
  plugins/action_update_review_status/src/databaseMethods.ts
  plugins/action_update_review_status/src/index.ts
  plugins/action_update_review_status/src/updateReviewsStatuses.test.ts
  plugins/action_update_review_status/src/updateReviewsStatuses.ts
  plugins/action_update_review_status/yarn.lock
  src/components/graphQLConnect.ts
  src/generated/graphql.ts
Labels: Bug: development, Feature: refactor

#960 #953 Fix to only show action SELF_ASSIGN while there are available_sections to be assigned
  database/buildSchema/43_views_functions_triggers.sql
Labels: Bug: development, Feature: refactor

#963 #961 File handling fixes
  plugins/action_generate_document/src/generateDoc.ts
  src/components/exportAndImport/importFromJson.ts
Labels: Bug: development, Config, Dev

#968 #967 Template category export/import fix
  database/snapshotOptions/templateExport.json
Labels: Bug: development, Bug: production

#980 #977 Re-write update review statuses action
  documentation/List-of-Action-plugins.md
  plugins/action_change_status/src/changeStatus.ts
  plugins/action_update_review_status/package.json
  plugins/action_update_review_status/plugin.json
  plugins/action_update_review_status/src/databaseMethods.ts
  plugins/action_update_review_status/src/index.ts
  plugins/action_update_review_status/src/updateReviewStatuses.ts
  plugins/action_update_review_status/yarn.lock
  src/components/actions/coreActions.ts
Labels: Bug: development, Bug: production, Customer: Fiji, Customer: Angola
