Repository openmsupply/conforma-server, pull requests merged in 2022-09, with the labels that each got.

#831 #820 improvement review responses part of latest review submission
  database/buildSchema/32_review_response.sql
  database/migration/migrateData.ts
Labels: Config, Dev, Bugs during tests

#828 #827 Fix for stray data in localisation (and prefs) folder
  src/components/snapshots/useSnapshot.ts
Labels: Bug: development, Phase 2, Approved: MVP

#840 #839 Re-instate action fail behaviour
  src/components/actions/processTrigger.ts
Labels: Bug: development, Approved: MVP

#841 820-part3 change to get is latest review before submission
  database/buildSchema/32_review_response.sql
  database/core_templates/info.json
  database/core_templates/options.json
  database/core_templates/schema_init.sql
  database/core_templates/snapshot.json
  database/migration/migrateData.ts
  src/generated/graphql.ts
Labels: Config, Dev, Bugs during tests

#846 #845 Fix for template version bug
  src/components/snapshots/triggerTables.ts
Labels: Bug: development, Phase 2

#847 Adding reviewer details on reviewData object accessible in actions
  src/components/graphQLConnect.ts
  src/types.ts
Labels: Feature: improvement, Dev, Phase 2

#857 #856 revokePermission changes
  documentation/List-of-Action-plugins.md
  plugins/action_revoke_permissions/src/databaseMethods.ts
  plugins/action_revoke_permissions/src/revokePermissions.ts
Labels: Phase 2, Approved: MVP

#859 #825 Data views -- discrete (non-overlapping) views
  database/buildSchema/44_data_view.sql
  database/migration/migrateData.ts
  documentation/API.md
  documentation/Data-View.md
  plugins/action_modify_record/src/databaseMethods.ts
  plugins/action_modify_record/src/modifyRecord.ts
  src/components/data_display/helpers.ts
  src/components/data_display/routes.ts
  src/components/data_display/types.ts
  src/components/postgresConnect.ts
  src/components/utilityFunctions.ts
  src/config.ts
  src/server.ts
Labels: Effort: 4, Feature: improvement, Conforma: Global budget
