Repository openmsupply/conforma-server, pull requests merged in 2022-08, with the labels that each got.

#783 #782 Allow non-answered elements to be reviewable (or not)
  database/buildSchema/16_template_element.sql
  database/migration/migrateData.ts
  plugins/action_trim_responses/src/trimResponses.ts
  plugins/action_trim_responses/src/trimResponsesWithoutDatabase.test.ts
  src/components/postgresConnect.ts
  src/generated/graphql.ts
Labels: Approved: MVP

#823 #822 Exclude prefs from repo
  .gitignore
  nodemon.json
  preferences/preferences.json
  src/loadPrefs.ts
  utils/build_all.sh
Labels: Bug: development, Phase 2

#824 Fix problem to show application in DRAFT (not yet submitted) in list to Reviewer
  database/core_templates/info.json
  database/core_templates/schema_init.sql
  database/core_templates/snapshot.json
Labels: Epic #62: View other's Review, Dev, Phase 2
